name: Scan Quotidien

on:
  schedule:
    - cron: '30 10 * * *' # 10h30 UTC soit 11h30 à Yaoundé
  workflow_dispatch: # Permet de lancer le scan manuellement à tout moment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          pip install requests

      - name: Lancement du script
        run: python Main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
